name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Save service account key
      run: |
        echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}" > ${{ github.workspace }}/service-account.json

    - name: Run your build or deploy script
      env:
        GCLOUD_KEY_FILE: ${{ github.workspace }}/service-account.json
      run: |
        # Contoh: npm install & npm run build atau deploy ke Cloud Run/Function
        npm install
        npm run build
        # misal: gcloud auth activate-service-account --key-file=$GCLOUD_KEY_FILE
        # lalu deploy pakai gcloud CLI atau tools lain
